# Generated by Django 3.0.6 on 2020-06-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200609_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('Writing', 'Writing'), ('Reading', 'Reading')], max_length=200, null=True),
        ),
    ]
